[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = true
enableXsrfProtection = false
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base="light"

[global]
showWarningOnDirectExecution = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
caching = false
